name: System Date

on:
  push:

jobs:
  print-date:
    runs-on: ubuntu-latest

    steps:
      - name: Отримання поточного системного часу
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
